# chroma_logging.yaml
# Chroma configuration file...
chroma_setting_1: value_1
chroma_setting_2: value_2
chroma_setting_3: value_3
chroma_setting_4: value_4
chroma_setting_5: value_5
chroma_setting_6: value_6
chroma_setting_7: value_7
chroma_setting_8: value_8
chroma_setting_9: value_9
chroma_setting_10: value_10
chroma_setting_11: value_11
chroma_setting_12: value_12
chroma_setting_13: value_13
chroma_setting_14: value_14
chroma_setting_15: value_15
chroma_setting_16: value_16
chroma_setting_17: value_17
chroma_setting_18: value_18
chroma_setting_19: value_19
chroma_setting_20: value_20
chroma_setting_21: value_21
chroma_setting_22: value_22
chroma_setting_23: value_23
chroma_setting_24: value_24
chroma_setting_25: value_25
chroma_setting_26: value_26
chroma_setting_27: value_27
chroma_setting_28: value_28
chroma_setting_29: value_29
chroma_setting_30: value_30
chroma_setting_31: value_31
chroma_setting_32: value_32
chroma_setting_33: value_33
chroma_setting_34: value_34
chroma_setting_35: value_35
chroma_setting_36: value_36
chroma_setting_37: value_37
chroma_setting_38: value_38
chroma_setting_39: value_39
chroma_setting_40: value_40
chroma_setting_41: value_41
chroma_setting_42: value_42
chroma_setting_43: value_43
chroma_setting_44: value_44
chroma_setting_45: value_45
chroma_setting_46: value_46
chroma_setting_47: value_47
chroma_setting_48: value_48
